---
- name: Remove default repos
  become: yes
  apt_repository: repo={{item}} state=absent
  with_items:
    - "deb http://httpredir.debian.org/debian jessie main"
    - "deb-src http://httpredir.debian.org/debian jessie main"


- name: Add Unizar repos
  become: yes
  apt_repository: repo={{item}} state=present
  with_items:
    - "deb http://softlibre.unizar.es/debian jessie main contrib non-free"
    - "deb-src http://softlibre.unizar.es/debian jessie main contrib non-free"
    - "deb http://softlibre.unizar.es/debian jessie-updates main contrib non-free"
    - "deb-src http://softlibre.unizar.es/debian jessie-updates main contrib non-free"
    - "deb http://security.debian.org/ jessie/updates main contrib non-free"
    - "deb-src http://security.debian.org/ jessie/updates main contrib non-free"    

- name: Update apt
  become: yes
  apt: 
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Install Extra Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{% if 'packages' in server %} {{server.packages | default({}) }} {% endif %} "
  when: server.packages   is defined

- name: Configure the timezone
  become: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: yes
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

#- name: Set default system language pack
#  shell: locale-gen {{server.locale}}
#  become: yes

- locale_gen:
    name: "{{server.locale}}"
    state: present
