---
- hostname:
    name: "{{ vagrant_local.vm.hostname }}"
    
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ vagrant_local.vm.hostname }}$' line="{{ vagrant_local.vm.ip }} {{vagrant_local.vm.hostname}}" state=present
  when: vagrant_local.vm.ip is defined
  with_items: groups['all']
  tags:
    - hosts